name: rise-environment
channels:
  - damianavila82
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - pandas
  - bokeh
  - rise
  - pdfkit
  - wkhtmltopdf
  - pip
  - pip:
    - jupyter_contrib_nbextensions
    - jupyter-server-proxy
    - hide_code

