name: rise-environment_plus_hide_code
channels:
  - damianavila82
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - pandas
  - bokeh
  - rise
  - pip
  - pip:
    - pdfkit
    - jupyter_contrib_nbextensions
    - hide_code==0.5.2

