name: rise-environment
channels:
  - damianavila82
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - pandas
  - bokeh
  - rise
  - pip
  - pip:
    - jupyter_contrib_nbextensions
    - hide_cod
