#!/bin/bash

# enable hide_code extension, see https://github.com/kirbs-/hide_code and 
# https://github.com/binder-examples/jupyter-extension/blob/master/postBuild
# with server extension based on https://github.com/matheusmota/facens-dataviz/blob/54cbfb373916c7180c65c2ed7500ac890252bd98/binder/postBuild
# and https://jupyter-notebook.readthedocs.io/en/4.x/examples/Notebook/rstversions/Distributing%20Jupyter%20Extensions%20as%20Python%20Packages.html#enable-a-server-extension
# and https://jupyter-notebook.readthedocs.io/en/4.x/examples/Notebook/rstversions/Distributing%20Jupyter%20Extensions%20as%20Python%20Packages.html#install-and-enable-the-server-extension-and-nbextension
#jupyter contrib nbextension install --user
jupyter nbextension install --sys-prefix hide_code
jupyter nbextension enable --sys-prefix hide_code
jupyter serverextension enable --sys-prefix jupyter_server_proxy
jupyter serverextension enable --sys-prefix hide_code